name: Testing config overrides
type: profile
description: 'Minimal profile for running tests with config overrides in a profile.'
# version: VERSION
# core: 8.x
hidden: true
dependencies:
  - action
  - language
  - tour

# Information added by Drupal.org packaging script on 2018-01-26
version: '8.4.4+15-dev'
core: '8.x'
project: 'drupal'
datestamp: 1517003251
